### ISSUE TITLE
Why 2 different servers/ports?

### ISSUE THREAD

**Issue by kevinSuttle** [kadira-samples/react-storybook-simple-demo#2]
Couldn't you use `process.env.PORT`? 

https://github.com/kadira-samples/react-storybook-simple-demo/blob/master/package.json#L7
https://github.com/kadira-samples/react-storybook-simple-demo/blob/master/server.js#L7

Like, what if you wanted to switch ports based on `NODE_ENV`?

**Comment by arunoda** [comment]
One in the package.json is for the storybook. Other one is for the actual app.

**Comment by kevinSuttle** [comment]
@arunoda Thanks. For some reason, I'm having trouble deploying a normal Storybook app to CloudFoundry.

Their Node buildpacks require port 3000 being mapped. 
`TIP: Application must be listening on the right port. Instead of hard coding the port, use the $PORT environment variable.`

So, I set this in my package.json scripts object:

```
"storybook-prod": "export PORT=3000 && start-storybook -p $PORT",`
```

Still doesn't work. Could very well be a CF thing, but wanted to check here first.

**Comment by kevinSuttle** [comment]
I gave up and tried https://zeit.co/now, which seemed to work great at first, but I can only get the UI to appear. 

<img width="1440" alt="screen shot 2016-05-05 at 3 01 11 pm" src="https://cloud.githubusercontent.com/assets/95672/15053919/f1f1a7ac-12d2-11e6-9c86-f089c838d6ad.png">

**Comment by kevinSuttle** [comment]
I even re-configured the paths so the directory wasn't hidden. I think this is a Zeit issue. It works locally.

![image](https://cloud.githubusercontent.com/assets/95672/15054518/edf831b8-12d5-11e6-8ec2-94cf2bacbaa8.png)
